"""
Grounded generation: answer only from the retrieved context, cite the
document IDs actually used, and abstain honestly when the context is weak.

The abstain threshold routes which system prompt is used - it does NOT
write the abstain message itself. That message is always generated by the
model, from the weak context it was actually given. A hardcoded refusal
string would be exactly the "canned if/else response" the PDF forbids.
See DECISIONS.md D-12.
"""

import config
from llm_client import call_llm

GROUNDED_SYSTEM_PROMPT = """You are a Q&A assistant for Northbay Commerce \
AI, a B2B retail and consumer AI vendor. Answer the question using ONLY \
the context passages below - never use outside knowledge, even if you \
believe you know the answer. If part of the question isn't supported by \
the context, leave that part out rather than guessing.

Write a clear, direct answer in plain prose.

After your answer, on a new line, write exactly:
Sources: <comma-separated document IDs you actually drew on>"""

ABSTAIN_SYSTEM_PROMPT = """You are a Q&A assistant for Northbay Commerce \
AI. The context passages below were retrieved but scored too low to \
reliably answer the question - they may be off-topic or only tangentially \
related.

Do not use outside knowledge and do not guess. Write a brief, honest reply \
that says you don't have enough information to answer this specific \
question, and briefly mentions what the retrieved context actually covers \
instead, so the user understands why. Base this only on what the context \
below actually says.

After your reply, on a new line, write exactly:
Sources: none"""


def _format_context(chunks):
    return "\n\n".join(f"[{c['doc_id']}]\n{c['text']}" for c in chunks)


def _parse_answer(raw):
    idx = raw.lower().rfind("sources:")
    if idx == -1:
        return raw.strip(), []

    answer = raw[:idx].strip()
    _, _, sources_value = raw[idx:].partition(":")
    sources_value = sources_value.strip()

    if sources_value.lower() in ("none", "n/a", ""):
        return answer, []
    return answer, [s.strip() for s in sources_value.split(",") if s.strip()]


def generate_answer(query, ranked_chunks):
    """ranked_chunks: output of rerank_candidates() - each carrying a
    "rerank_score". Returns a dict with the answer, verified citations,
    any invalid citations caught, and whether this was an abstain response.
    """
    top_score = (ranked_chunks[0].get("rerank_score") or 0) if ranked_chunks else 0
    is_weak = top_score < config.ABSTAIN_THRESHOLD

    system_prompt = ABSTAIN_SYSTEM_PROMPT if is_weak else GROUNDED_SYSTEM_PROMPT
    user_prompt = f"Context passages:\n{_format_context(ranked_chunks)}\n\nQuestion: {query}"

    raw = call_llm(system_prompt, user_prompt, purpose="generate")
    answer_text, cited_ids = _parse_answer(raw)

    # Never trust what the model claims it cited - check against the doc
    # IDs actually present in the context it was given. See DECISIONS.md D-13.
    valid_doc_ids = {c["doc_id"] for c in ranked_chunks}

    # A citation counts as verified if it was parsed cleanly from the
    # "Sources:" line, OR the doc ID simply appears anywhere in the raw
    # response - this second check recovers citations the model gave in a
    # different format (inline brackets, trailing punctuation) that a
    # strict line-parse would otherwise miss, without weakening the
    # fabrication check below (a made-up ID still won't match any real one).
    verified = {cid for cid in cited_ids if cid in valid_doc_ids}
    verified |= {doc_id for doc_id in valid_doc_ids if doc_id in raw}
    verified = sorted(verified)

    invalid = [cid for cid in cited_ids if cid not in valid_doc_ids]

    return {
        "query": query,
        "answer": answer_text,
        "cited_docs": verified,
        "invalid_citations": invalid,
        "abstained": is_weak,
        "top_score": top_score,
    }


if __name__ == "__main__":
    from retrieval import hybrid_search
    from rerank import rerank_candidates

    def run(label, query):
        print("=" * 70)
        print(f"{label}\nQuery: {query}\n")
        ranked = rerank_candidates(query, hybrid_search(query))
        result = generate_answer(query, ranked)
        print(f"Top score: {result['top_score']}  Abstained: {result['abstained']}")
        print(f"Cited: {result['cited_docs']}  Invalid citations: {result['invalid_citations']}")
        print(f"\n{result['answer']}\n")

    run("Test 1: well-covered question -> grounded answer with citation",
        "What version is the Shopify connector on?")

    # Test 2 checks the citation VALIDATOR itself, not the LLM - we can't
    # reliably make a real model hallucinate a citation on demand, but we
    # can prove the code catches one if it happens.
    print("=" * 70)
    print("Test 2: citation validator catches a fabricated doc ID\n")
    fake_chunks = [{"doc_id": "05_integration_guide", "text": "...", "rerank_score": 9.0}]
    _, cited = _parse_answer("Some answer.\nSources: 05_integration_guide, 99_fake_doc")
    valid_ids = {c["doc_id"] for c in fake_chunks}
    print(f"  Claimed citations: {cited}")
    print(f"  Verified: {[c for c in cited if c in valid_ids]}")
    print(f"  Invalid (would be flagged): {[c for c in cited if c not in valid_ids]}\n")

    # Note: the refund-policy question is deliberately NOT used here as the
    # abstain example - Phase 7 showed it scores 5.0, above threshold (a
    # real finding, see DECISIONS.md D-19), so it would NOT abstain today.
    # Headcount has no topically-adjacent chunk to cause that confusion.
    run("Test 3: genuine coverage gap -> abstain, model-generated",
        "How many employees does Northbay have?")
